// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShop.Infra.Persistence;

#nullable disable

namespace WebShop.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211211247_AddDataMoreData")]
    partial class AddDataMoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebShop.Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalInfo = "First seeded order - priority shipping",
                            OrderDate = new DateTime(2025, 12, 10, 21, 12, 46, 527, DateTimeKind.Utc).AddTicks(6231),
                            TotalPrice = 129.99m
                        },
                        new
                        {
                            Id = 2,
                            AdditionalInfo = "Second seeded order - gift wrap",
                            OrderDate = new DateTime(2025, 12, 9, 21, 12, 46, 527, DateTimeKind.Utc).AddTicks(6240),
                            TotalPrice = 49.50m
                        },
                        new
                        {
                            Id = 3,
                            AdditionalInfo = "Third seeded order - international",
                            OrderDate = new DateTime(2025, 12, 10, 21, 12, 46, 527, DateTimeKind.Utc).AddTicks(6241),
                            TotalPrice = 299.00m
                        });
                });

            modelBuilder.Entity("WebShop.Core.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 30,
                            SubTotal = 0m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            SubTotal = 0m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 1,
                            Quantity = 25,
                            SubTotal = 0m
                        });
                });

            modelBuilder.Entity("WebShop.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Badge")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = 0,
                            CreateUtc = new DateTime(2025, 12, 3, 22, 12, 46, 528, DateTimeKind.Local).AddTicks(3347),
                            ImageUrl = "1.jpg",
                            Price = 899.99m,
                            ProductCategoryId = 1,
                            ProductName = "Laptop",
                            SalePrice = 499.99m
                        },
                        new
                        {
                            Id = 2,
                            Badge = 1,
                            CreateUtc = new DateTime(2025, 12, 11, 22, 12, 46, 528, DateTimeKind.Local).AddTicks(3543),
                            ImageUrl = "2.jpg",
                            Price = 29.99m,
                            ProductCategoryId = 1,
                            ProductName = "Wireless Mouse",
                            SalePrice = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            Badge = 0,
                            CreateUtc = new DateTime(2025, 12, 8, 22, 12, 46, 528, DateTimeKind.Local).AddTicks(3548),
                            ImageUrl = "3.jpg",
                            Price = 149.50m,
                            ProductCategoryId = 2,
                            ProductName = "Office Chair",
                            SalePrice = 149.50m
                        },
                        new
                        {
                            Id = 4,
                            Badge = 0,
                            CreateUtc = new DateTime(2025, 12, 9, 22, 12, 46, 528, DateTimeKind.Local).AddTicks(3551),
                            ImageUrl = "4.jpg",
                            Price = 45.00m,
                            ProductCategoryId = 1,
                            ProductName = "Webcam HD 1080p",
                            SalePrice = 45.00m
                        },
                        new
                        {
                            Id = 5,
                            Badge = 2,
                            CreateUtc = new DateTime(2025, 12, 5, 22, 12, 46, 528, DateTimeKind.Local).AddTicks(3555),
                            ImageUrl = "5.jpg",
                            Price = 129.00m,
                            ProductCategoryId = 1,
                            ProductName = "Portable SSD 1TB",
                            SalePrice = 99.00m
                        },
                        new
                        {
                            Id = 6,
                            Badge = 1,
                            CreateUtc = new DateTime(2025, 12, 1, 22, 12, 46, 528, DateTimeKind.Local).AddTicks(3559),
                            ImageUrl = "6.jpg",
                            Price = 299.99m,
                            ProductCategoryId = 2,
                            ProductName = "Standing Desk",
                            SalePrice = 249.99m
                        },
                        new
                        {
                            Id = 7,
                            Badge = 0,
                            CreateUtc = new DateTime(2025, 12, 9, 22, 12, 46, 528, DateTimeKind.Local).AddTicks(3562),
                            ImageUrl = "7.jpg",
                            Price = 89.99m,
                            ProductCategoryId = 2,
                            ProductName = "Bookshelf Wooden",
                            SalePrice = 89.99m
                        },
                        new
                        {
                            Id = 8,
                            Badge = 0,
                            CreateUtc = new DateTime(2025, 12, 1, 22, 12, 46, 528, DateTimeKind.Local).AddTicks(3565),
                            ImageUrl = "8.jpg",
                            Price = 25.99m,
                            ProductCategoryId = 3,
                            ProductName = "Table Lamp LED",
                            SalePrice = 25.99m
                        },
                        new
                        {
                            Id = 9,
                            Badge = 0,
                            CreateUtc = new DateTime(2025, 12, 1, 22, 12, 46, 528, DateTimeKind.Local).AddTicks(3567),
                            ImageUrl = "9.jpg",
                            Price = 19.99m,
                            ProductCategoryId = 3,
                            ProductName = "Comfort Footrest",
                            SalePrice = 19.99m
                        });
                });

            modelBuilder.Entity("WebShop.Core.Entities.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Furniture"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Accessories"
                        });
                });

            modelBuilder.Entity("WebShop.Core.Entities.OrderLine", b =>
                {
                    b.HasOne("WebShop.Core.Entities.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.Core.Entities.Product", "Product")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebShop.Core.Entities.Product", b =>
                {
                    b.HasOne("WebShop.Core.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebShop.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("WebShop.Core.Entities.Product", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("WebShop.Core.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
