// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShop.Infra.Persistence;

#nullable disable

namespace WebShop.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205134741_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebShop.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "~/assets/imgs/shop/1.jpg",
                            Price = 899.99m,
                            ProductCategoryId = 1,
                            ProductName = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            CreateUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "~/assets/imgs/shop/2.jpg",
                            Price = 29.99m,
                            ProductCategoryId = 1,
                            ProductName = "Wireless Mouse"
                        },
                        new
                        {
                            Id = 3,
                            CreateUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "~/assets/imgs/shop/3.jpg",
                            Price = 149.50m,
                            ProductCategoryId = 2,
                            ProductName = "Office Chair"
                        },
                        new
                        {
                            Id = 4,
                            CreateUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "~/assets/imgs/shop/4.jpg",
                            Price = 199.00m,
                            ProductCategoryId = 1,
                            ProductName = "Monitor 24 Inch"
                        },
                        new
                        {
                            Id = 5,
                            CreateUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "~/assets/imgs/shop/5.jpg",
                            Price = 59.99m,
                            ProductCategoryId = 1,
                            ProductName = "Keyboard Mechanical"
                        },
                        new
                        {
                            Id = 6,
                            CreateUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "~/assets/imgs/shop/5.jpg",
                            Price = 59.99m,
                            ProductCategoryId = 1,
                            ProductName = "Keyboard Mechanical"
                        },
                        new
                        {
                            Id = 7,
                            CreateUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "~/assets/imgs/shop/7.jpg",
                            Price = 45.00m,
                            ProductCategoryId = 1,
                            ProductName = "Webcam HD 1080p"
                        },
                        new
                        {
                            Id = 8,
                            CreateUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "~/assets/imgs/shop/8.jpg",
                            Price = 129.00m,
                            ProductCategoryId = 1,
                            ProductName = "Portable SSD 1TB"
                        },
                        new
                        {
                            Id = 9,
                            CreateUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "~/assets/imgs/shop/9.jpg",
                            Price = 299.99m,
                            ProductCategoryId = 2,
                            ProductName = "Standing Desk"
                        },
                        new
                        {
                            Id = 10,
                            CreateUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "~/assets/imgs/shop/10.jpg",
                            Price = 89.99m,
                            ProductCategoryId = 2,
                            ProductName = "Bookshelf Wooden"
                        },
                        new
                        {
                            Id = 11,
                            CreateUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "~/assets/imgs/shop/11.jpg",
                            Price = 25.99m,
                            ProductCategoryId = 2,
                            ProductName = "Table Lamp LED"
                        },
                        new
                        {
                            Id = 12,
                            CreateUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "~/assets/imgs/shop/12.jpg",
                            Price = 19.99m,
                            ProductCategoryId = 2,
                            ProductName = "Comfort Footrest"
                        });
                });

            modelBuilder.Entity("WebShop.Core.Entities.ProductCategory", b =>
                {
                    b.Property<int>("CatergoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatergoryId"));

                    b.Property<string>("CatergoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatergoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CatergoryId = 1,
                            CatergoryName = "Electronics"
                        },
                        new
                        {
                            CatergoryId = 2,
                            CatergoryName = "Furniture"
                        },
                        new
                        {
                            CatergoryId = 3,
                            CatergoryName = "Accessories"
                        });
                });

            modelBuilder.Entity("WebShop.Core.Entities.Product", b =>
                {
                    b.HasOne("WebShop.Core.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebShop.Core.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
